services:
  - type: web
    name: ggf-geohub
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_UPLOADS
        value: "false"
